# Architecture
arch: cResNet18 

# ===== Dataset ===== #
data: dataset
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: sgd
learning_rate: 0.001
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: DenseConv
bn_type: LearnedBatchNorm
init: HeNormal
mode: fan_in
activation: ReLU

# ===== Hardware setup ===== #
workers: 4